// The provider repo's `.gitignore` — GENERATED, not templated, and it has
// to be.
//
// npm NEVER publishes a file named `.gitignore`. It sits on npm's own
// always-excluded list, and naming the parent directory in package.json
// `files` does not override it: `npm pack --dry-run` on this package omits
// `project/.sdk/tm/seneca-provider/.gitignore` while shipping every sibling
// in that folder. So the template worked from a checkout and reached NOBODY
// who installed @voxgig/sdkgen from the registry — their generated provider
// had no ignore file, and the very first regeneration left the repo dirty
// with the `.jostraca/` output duplicate this content exists to hide.
//
// Every one of the 23 language targets already emits its `.gitignore` from a
// `Gitignore_<lang>.ts` for this same reason. seneca-provider was the only
// target still doing it with a template, and the only one npm could break.
//
// `packaging.test.ts` asks npm directly whether every shipped file survives
// packing, so the next dotfile added to the scaffold cannot repeat this.
//
// The content below is the template's, byte for byte. It carried no
// placeholder, so nothing about `stdrep` substitution changes by moving it.

import {
  Content,
  File,
  cmp,
} from '@voxgig/sdkgen'


const Gitignore = cmp(async function Gitignore(_props: any) {
  File({ name: '.gitignore' }, () => {
    Content(`# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

*~

package-lock.json
yarn.lock

test/local-config.js
test/local-env.js
# TypeScript build info
*.tsbuildinfo
.tsbuildinfo/

# Generator bookkeeping. This package is GENERATED into this repo by
# @voxgig/sdkgen from the SDK project, and jostraca drops its meta log plus a
# full duplicate of the last generated output here on every run. The SDK repo
# commits its own copy; this repo has no reason to, and without this line
# every regeneration leaves the provider repo dirty with hundreds of
# untracked files.
.jostraca/
`)
  })
})


export {
  Gitignore
}
