import {
  Content,
  File,
  cmp,
} from '@voxgig/sdkgen'


const HEAD = `# GENERATED by @voxgig/sdkgen. Do not edit.

.PHONY: all build test clean reset sdk-src sdk-clean regen

all: build test

build:
\tnpm run build

test:
\tnpm test

clean:
\trm -rf dist dist-test .tsbuildinfo

reset:
\tnpm run reset

`


const INTRO_SDK = `# ---------------------------------------------------------------------------
# THIS REPOSITORY IS GENERATED, AND CAN REGENERATE ITSELF.
#
# Everything below fetches the SDK named in sdk-pin.json and runs the
# generator from it. Nothing here needs a sibling checkout or a particular
# directory layout: the pin names a repository and a TAG, and the checkout
# lands inside this repo at a fixed path.
#
# NOT a git submodule, deliberately. A submodule pins a commit in git's own
# plumbing, where a stale one is invisible in a normal diff and updating it is
# a second repository operation. sdk-pin.json is an ordinary committed file,
# regenerated from the model with everything else, so it moves with the SDK
# version it belongs to and shows up in review.
# ---------------------------------------------------------------------------`


// A provider whose builder is its own repository's .sdk/ (`output: root`).
const INTRO_SELF = `# ---------------------------------------------------------------------------
# THIS REPOSITORY IS GENERATED, BY ITS OWN BUILDER IN .sdk/.
#
# The builder generates this package and nothing else. Its API definition
# and guide are the SDK's: everything below fetches the SDK named in
# sdk-pin.json, and \`make regen\` replaces them with its own before
# generating, so the package is built from the same model as the SDK version
# it depends on.
#
# NOT a git submodule, deliberately. A submodule pins a commit in git's own
# plumbing, where a stale one is invisible in a normal diff and updating it is
# a second repository operation. sdk-pin.json is an ordinary committed file,
# regenerated from the model with everything else, so it moves with the SDK
# version it belongs to and shows up in review.
# ---------------------------------------------------------------------------`


const FETCH = `
SDK_PIN := sdk-pin.json
SDK_REPO := $(shell node -p "require('./$(SDK_PIN)').repo" 2>/dev/null)
SDK_TAG := $(shell node -p "require('./$(SDK_PIN)').tag" 2>/dev/null)
SDK_DIR := $(shell node -p "require('./$(SDK_PIN)').dir" 2>/dev/null)

# Point at a checkout you already have instead of fetching one:
#   make sdk-src SDK_SRC_FROM=../path/to/sdk
SDK_SRC_FROM ?=

# Fetch (or update) the SDK source at the pinned tag.
#
# A TAG, not a branch: the point is the exact revision this repository was
# generated from, so that regenerating reproduces what is committed here
# rather than whatever main happens to say today.
sdk-src:
\t@set -e; \\
\ttest -n "$(SDK_REPO)" || { echo "sdk-src: no repo in $(SDK_PIN)"; exit 1; }; \\
\ttest -n "$(SDK_TAG)" || { echo "sdk-src: no tag in $(SDK_PIN)"; exit 1; }; \\
\tif [ -n "$(SDK_SRC_FROM)" ]; then \\
\t  echo "sdk-src: using $(SDK_SRC_FROM) (not fetching)"; \\
\t  rm -rf "$(SDK_DIR)"; mkdir -p "$$(dirname "$(SDK_DIR)")"; \\
\t  ln -s "$$(cd "$(SDK_SRC_FROM)" && pwd)" "$(SDK_DIR)"; \\
\t  exit 0; \\
\tfi; \\
\tif [ -L "$(SDK_DIR)" ]; then \\
\t  echo "sdk-src: $(SDK_DIR) links to $$(readlink "$(SDK_DIR)"), which is left as it is;"; \\
\t  echo "         make sdk-clean first to fetch $(SDK_TAG) instead"; \\
\t  exit 0; \\
\tfi; \\
\tif [ -d "$(SDK_DIR)/.git" ]; then \\
\t  echo "sdk-src: fetching $(SDK_TAG) in $(SDK_DIR)"; \\
\t  git -C "$(SDK_DIR)" fetch --depth 1 origin "refs/tags/$(SDK_TAG):refs/tags/$(SDK_TAG)" 2>/dev/null || \\
\t    git -C "$(SDK_DIR)" fetch origin "refs/tags/$(SDK_TAG):refs/tags/$(SDK_TAG)"; \\
\t  git -C "$(SDK_DIR)" checkout -q "refs/tags/$(SDK_TAG)"; \\
\telse \\
\t  echo "sdk-src: cloning $(SDK_REPO) at $(SDK_TAG) into $(SDK_DIR)"; \\
\t  rm -rf "$(SDK_DIR)"; mkdir -p "$$(dirname "$(SDK_DIR)")"; \\
\t  git clone --depth 1 --branch "$(SDK_TAG)" "$(SDK_REPO).git" "$(SDK_DIR)"; \\
\tfi; \\
\techo "sdk-src: $(SDK_DIR) is at $(SDK_TAG)"

# Removes the fetched checkout AND the folder that held it. \`rm -rf\` on the
# checkout alone left an empty \`.sdksrc/\` behind — gitignored, so harmless,
# but it makes \`sdk-clean\` look like it did not finish. rmdir rather than
# another rm -rf: if anything else is in there, someone put it there, and
# removing it is not this target's business.
sdk-clean:
\trm -rf "$(SDK_DIR)"
\t@rmdir "$$(dirname "$(SDK_DIR)")" 2>/dev/null || true
`


const REGEN_SDK = `# Regenerate this repository from the pinned SDK.
#
# The SDK's model says where its provider goes, and that value is a fact about
# ONE developer's checkout layout — it cannot describe being cloned in here.
# So the destination is given to the generator AT RUN TIME instead:
#
#   path       ../..  — from the SDK checkout up to this repository root
#   enclosing  the output folder CONTAINS the SDK project, which the
#              generator refuses unless asked, because one \`..\` too many
#              writes a package over an unrelated repo
#
# See @voxgig/sdkgen docs/explanation/out-of-tree-targets.md.
# The generate-time output override arrived in @voxgig/sdkgen 4.16.0, and
# older versions IGNORE it SILENTLY: generation falls back to the destination
# in the SDK's own model, which from in here resolves to a folder that does
# not exist, gets skipped, and reports success having written nothing. That is
# not hypothetical — it is what this target did on its first end-to-end run,
# against a pin whose floor was set one release too low.
#
# So the floor is the version that actually ships the feature, not the version
# that happened to be current when it was written.
SDKGEN_MIN := 4.16.0

regen: sdk-src
\t@set -e; \\
\tif [ -L "$(SDK_DIR)" ]; then \\
\t  echo "regen: $(SDK_DIR) is a symlink, and regenerating through one writes"; \\
\t  echo "       the package somewhere else. Node resolves a module's own"; \\
\t  echo "       directory through symlinks, so the generator computes its"; \\
\t  echo "       destination from where the checkout REALLY is — not from"; \\
\t  echo "       here — and \\\`enclosing\\\` then permits the result."; \\
\t  echo "       SDK_SRC_FROM is for building and linking against a local"; \\
\t  echo "       SDK (make sdk-src). To regenerate, use a fetched checkout:"; \\
\t  echo "         make sdk-clean && make regen"; \\
\t  exit 1; \\
\tfi; \\
\techo "regen: building the generator in $(SDK_DIR)/.sdk"; \\
\tnpm --prefix "$(SDK_DIR)/.sdk" install; \\
\thave=$$(node -e "console.log(JSON.parse(require('fs').readFileSync('$(SDK_DIR)/.sdk/node_modules/@voxgig/sdkgen/package.json','utf8')).version)"); \\
\tnode -e 'const a=process.argv[1].split(".").map(Number),b=process.argv[2].split(".").map(Number); \\
\t  for(let i=0;i<3;i++){if(a[i]>b[i])process.exit(0);if(a[i]<b[i])process.exit(1)} process.exit(0)' \\
\t  "$$have" "$(SDKGEN_MIN)" || { \\
\t    echo "regen: $(SDK_TAG) uses @voxgig/sdkgen $$have, and regenerating from"; \\
\t    echo "       inside this repo needs >= $(SDKGEN_MIN) (the generate-time output"; \\
\t    echo "       override). Older versions IGNORE it and silently write nothing."; \\
\t    echo "       Pin a newer SDK tag, or regenerate from a checkout of the SDK."; \\
\t    exit 1; }; \\
\techo "regen: generating"; \\
\tcd "$(SDK_DIR)/.sdk" && \\
\t  SDKGEN_EXTERNAL='{"seneca-provider":{"path":"../..","enclosing":true}}' \\
\t  npm run generate
\t@echo "regen: done — review the diff in this repository"
`


const REGEN_SELF = `# Regenerate this repository with its own builder.
#
# The API definition and guide are replaced by the SDK source's first, so the
# builder generates from the SDK's model at the pinned tag, and generation
# checks the result against that source before writing. A linked checkout
# (SDK_SRC_FROM) is read as it is, and only this repository is written.
#
# To move to a newer SDK, set its version in .sdk/model/project.aontu and
# fetch that tag as you regenerate:
#
#   make regen SDK_TAG=v1.2.3
regen: sdk-src
\t@set -e; \\
\ttest -f .sdk/package.json || { echo "regen: no builder at .sdk/"; exit 1; }; \\
\tfor d in def model/guide; do \\
\t  test -d "$(SDK_DIR)/.sdk/$$d" || { echo "regen: no $(SDK_DIR)/.sdk/$$d"; exit 1; }; \\
\tdone; \\
\techo "regen: replacing the API definition and guide with those in $(SDK_DIR)"; \\
\tfor d in def model/guide; do \\
\t  rm -rf ".sdk/$$d"; mkdir -p ".sdk/$$d"; cp -R "$(SDK_DIR)/.sdk/$$d/." ".sdk/$$d/"; \\
\tdone; \\
\techo "regen: installing the builder"; \\
\tcd .sdk && npm install && \\
\techo "regen: generating" && \\
\tnpm run generate
\t@echo "regen: done — review the diff in this repository"
`


const Makefile = cmp(function Makefile(props: any) {
  const { provider } = props

  File({ name: 'Makefile' }, () => {
    Content([
      HEAD,
      provider.standalone ? INTRO_SELF : INTRO_SDK,
      FETCH,
      provider.standalone ? REGEN_SELF : REGEN_SDK,
    ].join('\n'))
  })
})


export {
  Makefile,
}
